import hero from "/assets/images/hero.jpeg";

export const heroImg = hero;

import hmv from "/assets/videos/hero.mp4";
import smallmv from "/assets/videos/smallHero2.mp4";
import highlightFirstmv from "/assets/videos/Spices.mp4";
import highlightSectmv from "/assets/videos/farminchillipowder.mp4";
import highlightThirdmv from "/assets/videos/farminturmericup.mp4";
import highlightFourthmv from "/assets/videos/farminmasala.mp4";
import exploremv from "/assets/videos/explore.mp4";
import framemv from "/assets/videos/frame.mp4";
import chillimv from "/assets/videos/chilli.mp4";

import apple from "/assets/images/apple.svg";
import pickling from "/assets/images/pickling.png";
import search from "/assets/images/search.svg";
import account from "/assets/images/account.svg"
import bag from "/assets/images/bag.svg";
import watch from "/assets/images/watch.svg";
import right from "/assets/images/right.svg";
import replay from "/assets/images/replay.svg";
import play from "/assets/images/play.svg";
import pause from "/assets/images/pause.svg";
import chilli1 from "/assets/images/chilli1.png";
import chilli2 from "/assets/images/chilli2.png";
import chilli3 from "/assets/images/chilli3.png";
import close from "/assets/images/close.svg";
import yellow from "/assets/images/yellow.jpg";
import blue from "/assets/images/blue.jpg";
import white from "/assets/images/white.jpg";
import black from "/assets/images/black.jpg";
import explore1 from "/assets/images/explore1.jpg";
import explore2 from "/assets/images/explore2.jpg";
import chip from "/assets/images/chip.jpeg";
import frame from "/assets/images/frame.png";
import  grannys  from '/assets/images/grannys.svg';
import  whatsapp from '/assets/images/whatsapp.svg';
import  womenimg from '/assets/images/womenfarm.png';
import  drychilli from '/assets/images/drychilli.png';
import about from "/assets/images/about.png";
import farmin from "/assets/images/farmin.png";
import chat from "/assets/images/chat.png";
import Order from "/assets/images/Order.png";
import logout from "/assets/images/logouts.png";

export const heroVideo = hmv;
export const logoutImg=logout;
export const OrderImg=Order;
export const closeImg=close;
export const farminImg=farmin;
export const chatImg=chat;
export const smallHeroVideo = smallmv;
export const highlightFirstVideo = highlightFirstmv;
export const highlightSecondVideo = highlightSectmv;
export const highlightThirdVideo = highlightThirdmv;
export const highlightFourthVideo = highlightFourthmv;
export const exploreVideo = exploremv;
export const frameVideo = framemv;
export const chilliVideo = chillimv;
export const womenImg=womenimg;
export const appleImg = apple;
export const accountImg=account;
export const grannysImg=pickling;
export const searchImg = search;
export const bagImg = bag;
export const watchImg = watch;
export const rightImg = right;
export const replayImg = replay;
export const playImg = play;
export const pauseImg = pause;
export const chilliimg=chilli1;
export const chilliimg2=chilli2;
export const chilliimg3=chilli3;
export const whatsappImg=whatsapp;
export const drychilliImg=drychilli;
export const aboutImg=about;

export const yellowImg = yellow;
export const blueImg = blue;
export const whiteImg = white;
export const blackImg = black;
export const explore1Img = explore1;
export const explore2Img = explore2;
export const chipImg = chip;
export const frameImg = frame;